### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by gurgeous** [pbhogan/sterile#13]
I'd be happy to write some. Let me know if you are interested. We are adopting Sterile for our project and I'd like to move it forward without pummeling you with issues :)

**Comment by pbhogan** [comment]
Hey Adam, I'm happy to take some PRs. I do try to actively maintain this gem but it comes in bursts when I can get to it usually.

**Comment by gurgeous** [comment]
Great! How about this?

- Ruby 2.7.x in .ruby-version
- `rake test` runs a single test (w/ Minitest)
- CI with github actions (test Ruby 2.7.x and Ruby 3.x)

I can also add rubocop if you want, but that would be more invasive.

**Comment by pbhogan** [comment]
Sounds good. We've still got a couple Ruby 2.3.x projects using this gem, but I don't think we need to test that.

I'll take PRs on the other issue you filed too, btw.
