### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by gurgeous** [pbhogan/sterile#9]
Thanks for creating such a great gem, and helping replace our old copy of stringex!

I'm getting a few errors when running tests. By default, rake runs with warnings turned on (like `ruby -w`). Here are the warnings:

```
sterile-1.0.21/lib/sterile/smart_format.rb:24: warning: ambiguous first argument; put parentheses or a space even after `/' operator
sterile-1.0.21/lib/sterile/titlecase.rb:114: warning: method redefined; discarding old smart_format_rules
sterile-1.0.21/lib/sterile/smart_format.rb:35: warning: previous definition of smart_format_rules was here
```

No rush, I can suppress these. Just letting you know. Thanks again!

**Comment by pbhogan** [comment]
Thanks!—fixed in 37caf71 

1.0.22 is pushed to RubyGems
